name: layout_flutter
description: A Flutter layout demo project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Pindahkan go_router ke sini, di bawah flutter: sdk: flutter
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Bagian assets tetap di bawah flutter:
  assets:
    - images/masjid.jpeg
    - images/km.jpg
    - images/pb.jpg
    - images/sepatu.webp
    - images/hedset.avif
    - images/jam.webp
    - images/ransel.webp